name: fahem
description: A new Flutter project.
publish_to: 'none'
version: 1.0.28+29

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #  device_preview: ^1.1.0
  intl: ^0.19.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.6
  url_launcher: ^6.2.3
  flutter_advanced_drawer: ^1.3.5
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  photo_view: ^0.14.0
  share_plus: ^7.2.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_holo_date_picker: ^1.1.3
  package_info_plus: ^5.0.1
  http: ^1.1.2
  http_parser: ^4.0.2
  pin_code_fields: ^8.0.1
  awesome_notifications: ^0.9.0
  font_awesome_flutter: ^10.6.0
  countup: ^0.1.4
  conditional_builder_null_safety: ^0.0.6
  file_picker: ^6.1.1
  badges: ^3.1.2
  audioplayers: ^5.2.1
  video_player: ^2.8.2
  flutter_staggered_grid_view: ^0.7.0
  animate_do: ^3.1.2
  flutter_rating_bar: ^4.0.1
  geolocator: ^10.1.0 # No (Linux)
  internet_connection_checker_plus: ^2.1.0
  image_picker: ^1.0.7 # No (Linux - MacOS - Windows)
  fluttertoast: ^8.2.4 # No (Linux - MacOS - Windows)
  cached_network_image: ^3.3.1 # No (Linux - Web - Windows)
  youtube_player_flutter: ^8.1.2 # No (Linux - MacOS - Web - Windows)
  vibration: ^1.8.4 # No (Linux - MacOS - Web - Windows)
  flutter_phoenix: ^1.1.1 # No (Linux - MacOS - Web - Windows)
  webview_flutter: ^4.4.4 # No (Linux - MacOS - Web - Windows)
  geocoding: ^2.1.1 # No (Linux - MacOS - Web - Windows)
  firebase_core: ^2.24.2 # No (Linux)
  firebase_auth: ^4.16.0 # No (Linux)
  cloud_firestore: ^4.14.0 # No (Linux - Windows)
  firebase_messaging: ^14.7.10 # No (Linux - Windows)
  google_sign_in: ^6.2.1 # No (Linux - MacOS - Windows)
  google_maps_flutter: ^2.5.2 # No (Linux - MacOS - Windows)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/flags/
    - assets/images/on_boarding/
    - assets/icons/
    - assets/lottie/
    - assets/svg/
    - assets/sounds/
    - assets/videos/

  fonts:
    - family: MontserratArabic
      fonts:
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-Black-900.otf
          weight: 900
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-ExtraBold-800.otf
          weight: 800
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-Bold-700.otf
          weight: 700
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-SemiBold-600.otf
          weight: 600
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-Medium-500.otf
          weight: 500
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-Regular-400.otf
          weight: 400
        - asset: assets/fonts/MontserratArabic/Montserrat-Arabic-Light-300.otf
          weight: 300

    - family: AvenirArabic
      fonts:
        - asset: assets/fonts/AvenirArabic/AvenirArabicBlack.ttf
          weight: 900
        - asset: assets/fonts/AvenirArabic/AvenirArabicHeavy.ttf
          weight: 700
        - asset: assets/fonts/AvenirArabic/AvenirArabicMedium.ttf
          weight: 500
        - asset: assets/fonts/AvenirArabic/AvenirArabicLight.ttf
          weight: 300